### ISSUE TITLE
deleting the service twice causes error.

### ISSUE THREAD

**Issue by portlek** [Dyescape/Bungeekube#1]
https://github.com/Dyescape/Bungeekube/blob/f2c0ee8cd905b6572c235f35e760fd70b81e7529/kubernetes/src/main/java/com/dyescape/bungeekube/kubernetes/discovery/watcher/KubernetesDiscoveryWatcher.java#L43
this line causes the error.

**Comment by MrDienns** [comment]
Hey there, do you mind providing more information than just a line? We have been using this plugin for an extended period (on Velocity) and have not faced errors. You should provide at least a stacktrace and logs when opening bugs.

**Comment by portlek** [comment]
```
[18:19:19 ERROR]: Exception in task tr.com.infumia.infumialib.platform.velocity.Initializer$$Lambda$635/0x0000000801217d48@60196094 by plugin InfumiaLib
java.lang.IllegalArgumentException: Server with name gameplay-dfc7dddd9-s72lf is not registered!
at com.velocitypowered.proxy.server.ServerMap.unregister(ServerMap.java:101) ~[server.jar:3.0.1]
at com.velocitypowered.proxy.VelocityServer.unregisterServer(VelocityServer.java:671) ~[server.jar:3.0.1]
at tr.com.infumia.infumialib.platform.velocity.kubernetes.VelocityDiscoveryWatcher.removeServer(VelocityDiscoveryWatcher.java:61) ~[?:?]
at tr.com.infumia.infumialib.platform.velocity.kubernetes.VelocityDiscoveryWatcher.onDelete(VelocityDiscoveryWatcher.java:39) ~[?:?]

----------------------
This Line is in the image.
We call handleDeletedService which runs this.watcher.onDelete(currentService); and also we run this.watcher.onDelete(currentService); after the calling handle delete method.

at tr.com.infumia.infumialib.kubernetes.DiscoveryScanner.scan(DiscoveryScanner.java:48) ~[?:?]
----------------------

at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[server.jar:3.0.1]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
```
![image](https://user-images.githubusercontent.com/12835420/141833922-5c28efb0-70ea-4179-a4d1-eb20e330bee8.png)

**Comment by portlek** [comment]
after deleting the line, no error or anything. 
![image](https://user-images.githubusercontent.com/12835420/141835552-5fc8280d-4c1e-44cb-b9cb-89d02d940f06.png)
![image](https://user-images.githubusercontent.com/12835420/141835573-38b3a6e0-d3ba-46a9-9c53-9375ca22b6b4.png)
